# Generated by Django 4.0.4 on 2022-05-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('agelimit', models.IntegerField()),
                ('sons', models.IntegerField(default=5)),
                ('emailadd', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=10)),
                ('occupation', models.CharField(default='not available', max_length=20)),
            ],
        ),
    ]
